### PR TITLE
Migrate to AndroidX and add Changelog

### LINKED ISSUE #5: Resource linking failed
```
$ flutter build apk
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.8s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /home/nightwelf/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+1/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/nightwelf/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.0+2/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':flutter_native_timezone:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/nightwelf/Projects/corp/build/flutter_native_timezone/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /home/nightwelf/Projects/corp/build/flutter_native_timezone/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /home/nightwelf/Projects/corp/build/flutter_native_timezone/intermediates/res/merged/release/values/values.xml:2601: error: resource android:attr/fontVariationSettings not found.
  /home/nightwelf/Projects/corp/build/flutter_native_timezone/intermediates/res/merged/release/values/values.xml:2602: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 40s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      41.2s
Gradle task assembleRelease failed with exit code 1
```

### PR DESCRIPTION
**Pull request by amitkhairnar44**
This PR fixes #5

### CODE REVIEW

**Comment by pinkfish** [comment]
Looks like we should add example/build into the .gitignore :)  Could you do that?

The rest looks good.

**Comment by amitkhairnar44** [comment]
@pinkfish It's already there in [.gitignore](https://github.com/pinkfish/flutter_native_timezone/blob/67f5d95e508e5d80e5a21e902094d38a342a396b/.gitignore#L10)  🙂

**Comment by amitkhairnar44** [comment]
@pinkfish Is it okay or it needs more changes?

**Comment by pinkfish** [comment]
Opps, sorry.  Looks good.

**Pull request merged**
